openapi: 3.0.1
info:
  title: AML
  description: Aml
  version: 1.0.0
servers:
  - url: 'https://gateway.cyberstarpay.com/aml'
security:
  - default: []
paths:
  /document/upload:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
      security:
        - default: []
      x-throttling-tier: Unlimited
      x-auth-type: Application & Application User
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
  '/document/update/{docid}':
    put:
      parameters:
        - name: docid
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
      security:
        - default: []
      x-throttling-tier: Unlimited
      x-auth-type: Application & Application User
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
  '/getVerificationResult/{documentId}/{tenantId}/{organizationId}':
    get:
      parameters:
        - name: documentId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: tenantId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: organizationId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        default:
          description: Default response
      security:
        - default: []
      x-throttling-tier: Unlimited
      x-auth-type: Application & Application User
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
  '/document/{documentId}/status':
    put:
      parameters:
        - name: documentId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
      security:
        - default: []
      x-throttling-tier: Unlimited
      x-auth-type: Application & Application User
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
  '/document/{documentId}':
    get:
      parameters:
        - name: documentId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        default:
          description: Default response
      security:
        - default: []
      x-throttling-tier: Unlimited
      x-auth-type: Application & Application User
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
  '/get-documents/{purpose}/{organizationId}':
    get:
      parameters:
        - name: purpose
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: organizationId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        default:
          description: Default response
      security:
        - default: []
      x-throttling-tier: Unlimited
      x-auth-type: Application & Application User
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
components:
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://test.com'
          scopes: {}
x-wso2-auth-header: Authorization
x-wso2-cors:
  corsConfigurationEnabled: true
  accessControlAllowOrigins:
    - '*'
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
    - authorization
    - Access-Control-Allow-Origin
    - Content-Type
    - SOAPAction
    - apikey
    - Internal-Key
    - 'content-disposition '
    - 'filename '
    - transfer-encoding
    - x-powered-by
    - date
    - keep-alive
  accessControlAllowMethods:
    - GET
    - PUT
    - POST
    - DELETE
    - PATCH
    - OPTIONS
x-wso2-production-endpoints:
  urls:
    - 'https://endpoint-sandbox.local.sepa-cyber.com/aml'
  type: http
x-wso2-sandbox-endpoints:
  urls:
    - 'https://endpoint-sandbox.local.sepa-cyber.com/aml'
  type: http
x-wso2-basePath: /aml/1.0.0
x-wso2-transports:
  - http
  - https
x-wso2-response-cache:
  enabled: false
  cacheTimeoutInSeconds: 300
